AWSTemplateFormatVersion: "2010-09-09"
Description: "ChangeSet"

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    Description: Select EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-0dba2cb6798deb6d8
      KeyName: MYLABKEY # define the key name
      UserData:
        Fn::Base64:
          !Sub
            - |
              #!/bin/bash
              apt-get update -y
              apt-get install docker-compose -y
              mkdir /home/ubuntu/${DirName}
            - { DirName: !Join [ "-", [ !Ref AWS::StackName, !Ref AWS::Region, "customdir" ] ] }

      # KeyName: my-key-pair # Replace with your key pair name
# mkdir /home/ubuntu/${AWS::Region} 

# ${VarName}  is replaced with the value of the variable VarName.

Outputs:
  InstanceId:
    Value: !Ref Instance            

# YouTube Link: https://www.youtube.com/watch?v=UrY1B9bf6p0&list=PL5KTLzN85O4LNGYy-dm1wJ-sKE5l4b5P5&index=11