AWSTemplateFormatVersion: "2010-09-09"
Description: "ChangeSet"

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    Description: Select EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-0dba2cb6798deb6d8
      KeyName: MYLABKEY # define the key name
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            apt-get update -y
            apt-get install docker-compose -y
            mkdir /home/ubuntu/sample

      # KeyName: my-key-pair # Replace with your key pair name

Outputs:
  InstanceId:
    Value: !Ref Instance            
