Description: "Create EC2 instance"

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
      - qa

Mappings:
  EnvMap: #logical id/name
    dev:
      InstanceType: "t2.large"
      name: "dev"
    qa:
      InstanceType: "t2.medium"
      name: "qa"
    prod:
      InstanceType: "t2.xlarge"
      name: "prod"

Resources:
  Instance: #logical id/name
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvMap, !Ref Environment, InstanceType]
      ImageId: ami-0dba2cb6798deb6d8
      Tags:
        - Key: "Name"
          Value: !FindInMap [EnvMap, !Ref Environment, name]

Outputs:
  InstanceName:
    Value: !Ref Instance