AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 instance | Select"

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - qa

Conditions:
  CreateResources: 
    Fn::Equals: 
      - Ref: Environment
      - qa

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 
        Fn::If:
          - CreateResources
          - Fn::Select: 
              - 0
              - - t2.micro
                - m1.large
          - Fn::Select:
              - 1
              - - t2.micro
                - m1.large
      ImageId: ami-0dba2cb6798deb6d8