AWSTemplateFormatVersion: "2010-09-09"
Description: "ChangeSet"

Parameters:
  S3BucketName:
    Description: Enter S3 bucket name
    Type: String

  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    Description: Enter EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
  
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-0dba2cb6798deb6d8
      # KeyName: my-key-pair # Replace with your key pair name

Outputs:
  BucketName:
    Value: !Ref S3Bucket
